# -*- mode: ruby -*-
# vi: set ft=ruby :


# osx-yosemite
Vagrant.configure(2) do |config|
  
  config.vm.box = "jhcook/osx-yosemite-10.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.91"
  config.vm.synced_folder "../shared", "/vagrant_data"


end
